### ISSUE TITLE
Beta version in App Store is not compatible

### ISSUE THREAD

**Issue by sossienl** [athombv/com.lg.ir#2]
10 days in the AppStore and It's not compatible with 1.3.2 so please remove it or fix it.

**Comment by BasKiers** [comment]
Hi, 

This app is only compatible with Homey v1.5 or above. This version of Homey client is currently in the testing phase and users who are testing Homey 1.5 are also able to test this app. I cannot comment on when Homey 1.5 comes to the stable or experimental channel. 

Regards,
Bas
